"Blobs"
asuc-octo/berkeley-mobile-ios pull request #205
Opened 2020-09-19 22:22 UTC by Stereopoly

| iPhone 8  | iPhone 8 Max   |  iPhone 11 Pro Max |
|---|---|---|
| ![Simulator Screen Shot - iPhone 8 - 2020-09-19 at 15 16 48](https://user-images.githubusercontent.com/7193442/93690256-308a7580-fa8b-11ea-9d80-ff8a5a06b12e.png) |  ![Simulator Screen Shot - iPhone 8 Plus - 2020-09-19 at 15 19 26](https://user-images.githubusercontent.com/7193442/93690300-8b23d180-fa8b-11ea-90d2-0e3ab1892b25.png)| ![Simulator Screen Shot - iPhone 11 Pro Max - 2020-09-19 at 15 20 52](https://user-images.githubusercontent.com/7193442/93690318-c2927e00-fa8b-11ea-8fb2-e126fb8bc0f1.png) |
| ![Simulator Screen Shot - iPhone 8 - 2020-09-19 at 15 16 51](https://user-images.githubusercontent.com/7193442/93690259-3718ed00-fa8b-11ea-89f2-625b3bf9b9fe.png) | ![Simulator Screen Shot - iPhone 8 Plus - 2020-09-19 at 15 19 29](https://user-images.githubusercontent.com/7193442/93690301-8e1ec200-fa8b-11ea-805a-5bbcd008ee22.png) | ![Simulator Screen Shot - iPhone 11 Pro Max - 2020-09-19 at 15 20 54](https://user-images.githubusercontent.com/7193442/93690319-c45c4180-fa8b-11ea-8bbe-2022288eb675.png) |

2020-09-19 22:52 UTC, KevWho requested changes
Couple visual issues with the 1st Gen SE.
Overlapping text. The "What do you need?" text is so long, blobs just might not be possible. If you wanted to add them, I'd set a constraint to enforce padding between the blob and the text, wrapping the text to two lines
<img width="504" alt="Screen Shot 2020-09-19 at 3 48 51 PM" src="https://user-images.githubusercontent.com/41145903/93690654-d809a700-fa8f-11ea-8c43-3cb6c3829e7d.png">
Gap at the top of the screen:
<img width="460" alt="Screen Shot 2020-09-19 at 3 48 48 PM" src="https://user-images.githubusercontent.com/41145903/93690657-dc35c480-fa8f-11ea-890d-0c2aea7ffae8.png">

2020-09-19 22:52 UTC, KevWho commented on berkeley-mobile/Calendar/CalendarViewController.swift
> +}
Could you move this to Utils, so it is easier to find for other classes?

2020-09-19 22:52 UTC, KevWho commented on berkeley-mobile/Calendar/CalendarViewController.swift
> +            let top = UIApplication.shared.windows[0].safeAreaInsets.top
I know this is unlikely to cause any issues, but could you use `.first` instead of `[0]` and safely unwrap it? Just in case, haha.

2020-09-19 23:19 UTC, KevWho commented on berkeley-mobile/Calendar/CalendarViewController.swift
> +            let top = UIApplication.shared.windows[0].safeAreaInsets.top
Just noticed you check if `.count == 0` in the line above, so ignore this comment.

2020-09-20 00:23 UTC, KevWho commented
Looks like the vertical spacing issue was indeed an issue with the height of the image view being too large. I pushed a commit that constrains the aspect ratio of the image view to match that of the displayed image, and that seems to have fixed the issue.

It also looks like `.topAnchor` already refers to the top of the screen, below the status bar, so I fixed up some things regarding that constraint as well.

2020-09-26 21:26 UTC, KevWho commented
How it looks on SE (1st gen) now:
<img width="1792" alt="Screen Shot 2020-09-26 at 2 23 27 PM" src="https://user-images.githubusercontent.com/41145903/94350574-37256980-0004-11eb-8068-1cee60fdd45e.png">

2020-09-26 21:46 UTC, Stereopoly commented
Tested on all other devices bar se1

2020-09-26 21:47 UTC, KevWho approved these changes

2020-09-26 21:47 UTC, merged