implemented displaying user location & user location button
asuc-octo/berkeley-mobile-ios pull request #209
Opened 2020-09-26 22:51 UTC by Cuiboy

MapView now displays user location. I also added a button that jumps to user's current location.

2020-09-27 00:13 UTC, huangshawn1 requested changes
requesting some minor changes, but looks good overall

2020-09-27 00:13 UTC, huangshawn1 commented on berkeley-mobile/Map/MapViewController.swift
> +        userLocationButton.layer.shadowOffset = CGSize(width: 0, height: 10)
shadow looks a bit different from FilterViewCell but I might just be seeing wrong. want to make sure the shadow stays consistent

2020-09-27 00:13 UTC, huangshawn1 commented on berkeley-mobile/Map/MapViewController.swift
> +        userLocationButton.alpha = 0
use hidden instead

2020-09-27 20:40 UTC, huangshawn1 approved these changes

2020-09-28 02:36 UTC, Stereopoly requested changes
Button looks great! Small nit - could you offset the position so the arrow looks a bit more centered in the circle?
Also a slight bug - If you move the map, the button disappears and never reappears. Only if I press the button, move the map, then the button reappears.

2020-10-03 21:42 UTC, Stereopoly commented
New button works well!
Minor issue here:
![Simulator Screen Shot - iPhone 11 Pro - 2020-10-03 at 14 41 41](https://user-images.githubusercontent.com/7193442/95002245-921c0b00-0586-11eb-8b96-0362f12ef673.png)

2020-10-03 21:51 UTC, Stereopoly commented on berkeley-mobile/Map/MapViewController.swift
> +        setUpUserLocationButton()
Move to viewDidLoad instead so it doesn't keep adding a button

2020-10-10 22:28 UTC, Stereopoly commented
lgtm!

2020-10-10 22:28 UTC, Stereopoly approved these changes

2020-10-10 22:28 UTC, merged