Add tappable fields in Overview cards
asuc-octo/berkeley-mobile-ios pull request #213
Opened 2020-10-03 23:18 UTC by Stereopoly

* Please test! (on actual devices too, since no Phone on sim)

![Simulator Screen Shot - iPhone 11 Pro - 2020-10-03 at 16 17 44](https://user-images.githubusercontent.com/7193442/95003415-06a97680-0594-11eb-9ab0-317da2809fbf.png)
![Simulator Screen Shot - iPhone 11 Pro - 2020-10-03 at 16 17 52](https://user-images.githubusercontent.com/7193442/95003418-08733a00-0594-11eb-95ce-8ad8f4b39a81.png)

2020-10-04 22:13 UTC, KevWho requested changes
Nice, works great on my device. Requested a few changes.

2020-10-04 22:13 UTC, KevWho commented on berkeley-mobile/Utils/UIViewController+Extensions.swift
> +                    UIApplication.shared.open(number, options: [:])
Wonder if you should add a check using `UIApplication.shared.canOpenURL(_:)` before showing the alert or display some sort of response on failure. As is, if the number cannot be dialed (e.g. the user is on an iPad w/o a SIM or something) nothing happens after the user presses "Yes", which might be a bit confusing.

2020-10-04 22:13 UTC, KevWho commented on berkeley-mobile/Common/DetailView/OverviewCardView.swift
> +            UIApplication.shared.windows.first!.rootViewController!.presentAlertLinkMaps(title: "Are you sure you want to open Maps?", message: "Berkeley Mobile wants to navigate to \(self.addressLab
Some items have addresses but no longitude / latitude (e.g. Suicide Resource Prevention Center). Tapping the address for these items opens Maps to the middle of the ocean (0, 0). Maybe you could make all the properties (or just lat / lon) in `DetailTapGestureRecognizer` optional and do some quick nil checks at the top of these functions?

2020-10-10 19:25 UTC, Stereopoly commented on berkeley-mobile/Common/DetailView/OverviewCardView.swift
> +            UIApplication.shared.windows.first!.rootViewController!.presentAlertLinkTelephone(title: "Are you sure you want to open Phone?", message: "Berkeley Mobile wants to call \(gesture.phoneNum
Ooh ya def don't need an alert then

2020-10-10 22:40 UTC, KevWho approved these changes
Mapping works! I'm sure we might discover some edge cases in the future where it does something unexpected, though, haha

2020-10-10 22:40 UTC, merged