Add events to calendar (fitness classes, academic & career events)
asuc-octo/berkeley-mobile-ios pull request #233
Opened 2020-11-08 00:06 UTC by huangshawn1

Allows users to tap fitness class cells, academic cells, or buttons in career event details to add an event to their Apple calendar.

- EventManager: class to manage all interaction with user's calendar, set parameters for added event
- CalendarEvent
  - additionalDescription: allows different classes to include different elements in the notes/description section of the event. this appears in addition to the "description" string. (e.g. trainer, register link)
  - addToDeviceCalendar: prompts the user with an alert if they want to add the event to their calendar

Also removed fitness class upcoming card and changed the "Today" card to show all future classes.
Added message to display when requesting calendar permission, modified location access message to better reflect what location is used for.

Screenshots:
![IMG_1836](https://user-images.githubusercontent.com/20230668/98453888-0bbd9080-2113-11eb-9671-de772e6c2d3f.PNG)
![IMG_1838](https://user-images.githubusercontent.com/20230668/98453893-11b37180-2113-11eb-8f45-721cab44b4c4.PNG)
![IMG_1839](https://user-images.githubusercontent.com/20230668/98453895-16782580-2113-11eb-9a6e-f5aa7990a34b.jpg)
![IMG_1840](https://user-images.githubusercontent.com/20230668/98453896-1841e900-2113-11eb-83c8-aac797c17023.PNG)

2020-11-08 00:41 UTC, Stereopoly commented
Lgtm! I think it's slightly on the fast side though, maybe increase duration slightly

2020-11-15 01:01 UTC, KevWho requested changes
Works well, changes look good! Talked with Sud briefly about getting a "full-day" field for the events that last all day, so hopefully those events will be better added to calendars in the future.

2020-11-15 01:12 UTC, huangshawn1 commented on berkeley-mobile/Fitness/FitnessViewController.swift
> +        tableView.deselectRow(at: indexPath, animated: false)
set to true because it's true everywhere else in the app

2020-11-15 21:54 UTC, KevWho approved these changes
Looks good to me! @Stereopoly looks like the duration for the success alert was increased to 0.7, does this address your comment?

2020-11-22 00:03 UTC, merged