added page
asuc-octo/berkeley-mobile-ios pull request #279
Opened 2021-04-10 21:51 UTC by Kwang8

Added a new page for Sproul.club, basically just followed this:

https://www.google.com/search?q=web+view+xcode&oq=web+view+xcode&aqs=chrome..69i57j0i10l9.1773j0j9&sourceid=chrome&ie=UTF-8

2021-04-10 22:33 UTC, huangshawn1 requested changes
It looks like the SproulClub folder isn't actually a group in the project (so I wasn't initially able to build the app). You want to add the folder as a group to the project (you should see the folder in the left project navigator in Xcode).

We want some spacing between the web view and the top/left/right/bottom elements. Typically, we use 6, 10, or 16 in other parts of the app but see what looks good.
It'd also be nice to disable the vertical scrolling indicator (we do that throughout the app) if possible. And disabling the pinch to zoom out would also be nice.

2021-04-10 23:15 UTC, Kwang8 reviewed
Moved everything into viewDidLoad. Added some constraints to the top, bottom, left, and right anchors. Disabled the vertical scroll indicator and pinch gestures.

2021-04-11 00:23 UTC, huangshawn1 commented
looks like the pinch gesture is still possible, I left a video on the Notion task: https://www.notion.so/berkeleymobile/Sprint-Board-iOS-3a44a1f5f7044adab2ea4b7827e7ea5c?p=60ca72b99d2b414fb1a743147d771258
take another look, but if it's too difficult to disable that's fine.

forgot to mention this, but can we also move this resource towards the front of the list? having it as the 2nd one (right after Dashboard) would be good.

2021-04-11 00:27 UTC, huangshawn1 commented on berkeley-mobile/Resources/SproulClub/SproulClubViewController.swift
> +            webView.load(myRequest)
nitpick: change variable names (don't use my...)

2021-04-11 00:27 UTC, huangshawn1 commented on berkeley-mobile/Resources/SproulClub/SproulClubViewController.swift
> +            webView.uiDelegate = self
I think the indent for viewDidLoad is off by 1

2021-04-17 21:51 UTC, huangshawn1 approved these changes
looks good

2021-04-17 22:00 UTC, merged