Dark Mode
asuc-octo/berkeley-mobile-ios pull request #295
Opened 2021-11-04 00:37 UTC by objorkman

* Berkeley Mobile joins the dark side
![Simulator Screen Shot - iPhone 13 Pro - 2021-11-03 at 17 37 02](https://user-images.githubusercontent.com/7193442/140237984-9d2e48f5-febb-4508-862b-6c61d1efb518.png)

2021-11-04 01:14 UTC, KevWho requested changes

2021-11-04 01:14 UTC, KevWho commented on berkeley-mobile/Tab Bar/TabBarController.swift
> +
Is this needed? It seems the same as [line 33](https://github.com/asuc-octo/berkeley-mobile-ios/blob/73daeb2f312c93573999c792323a99fe135de7f3/berkeley-mobile/Tab%20Bar/TabBarController.swift#L33) above.

2021-11-04 01:14 UTC, KevWho commented on berkeley-mobile/Assets/Colors/Colors+Calendar.swift
> +                    UIColor(red: 98.0 / 255.0, green: 97.0 / 255.0, blue: 98.0 / 255.0, alpha: 1.0)
I guess we should probably stick to either `UIColor(displayP3Red: ...)` or `UIColor(red: ...)` for consistency.

2021-11-04 01:14 UTC, KevWho commented on berkeley-mobile.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = K8FUZZ3FQV;
We should probably keep the old development team

2021-11-04 01:18 UTC, KevWho requested changes
This is a bit difficult to see (zoom in), but on the dining menus, the tableview background is white, so there's a sharp white rectangular around the dining items. Might be better to make the background for this table clear and have the cells be white for more contrast.

<img width="617" alt="Screen Shot 2021-11-03 at 6 15 05 PM" src="https://user-images.githubusercontent.com/41145903/140241031-fc3d22c8-0c3f-4b9c-acba-9411138e43d9.png">

2021-11-04 01:37 UTC, huangshawn1 requested changes
the table here also has a rectangular background, should make it transparent
![IMG_2605](https://user-images.githubusercontent.com/20230668/140242649-68d97e54-61b9-42de-8be8-17452f5db8f5.PNG)

2021-11-04 01:56 UTC, huangshawn1 commented
looks like there's some issues with dark mode in study pact creation pages. I'm not in any StudyPact groups but we should also test that the group pages work
![IMG_2607](https://user-images.githubusercontent.com/20230668/140244451-dbc63d5a-9b5e-4667-88c0-a2d122891619.PNG)
![IMG_2608](https://user-images.githubusercontent.com/20230668/140244455-854438b7-11d1-459e-98d0-24e694b8032d.PNG)

2022-04-09 01:09 UTC, KevWho approved these changes
LGTM!

2022-04-09 01:09 UTC, huangshawn1 approved these changes

2022-04-09 01:09 UTC, merged