profile page phone number add example
asuc-octo/berkeley-mobile-ios pull request #302
Opened 2022-10-08 00:22 UTC by sydneytsai

- changed phoneTextField from a BorderedTextField to a TaggedTextField in order to add a description underneath the input box
- modified the corresponding code for phoneTextField based on the change
- added an example under the input box "ex. 1234567890" to specify for the users that the phone number can only consist of numbers

2022-10-08 00:37 UTC, huangshawn1 requested changes

2022-10-08 00:37 UTC, huangshawn1 commented on berkeley-mobile/StudyPact/Profile/ProfileViewController.swift
> +        phoneField.textField.keyboardType = .URL
keyboard type probably shouldn't be .URL in this case

2022-10-08 00:37 UTC, huangshawn1 commented on berkeley-mobile/StudyPact/Profile/ProfileViewController.swift
> -        phoneTextField = phoneField
we'll probably want to keep this here instead of moving it

2022-10-08 00:37 UTC, huangshawn1 commented on berkeley-mobile/StudyPact/Profile/ProfileViewController.swift
> +
nit: don't need extra whitespace

2022-10-14 23:33 UTC, sydneytsai commented
I pushed the requested changes!

2022-10-14 23:56 UTC, huangshawn1 approved these changes
lgtm

2022-10-15 00:03 UTC, merged